import { MigrationInterface, QueryRunner } from "typeorm";

export class InitEntity1766595895535 implements MigrationInterface {
    name = 'InitEntity1766595895535'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`FK_385dd167bc3fe894f301c7537bb\` ON \`files\``);
        await queryRunner.query(`DROP INDEX \`FK_63c92c51cd7fd95c2d79d709b61\` ON \`files\``);
        await queryRunner.query(`DROP INDEX \`FK_b3c17c323fdc479a109e517f138\` ON \`files\``);
        await queryRunner.query(`ALTER TABLE \`task_assignees\` CHANGE \`assigned_at\` \`assigned_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`task_logs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_post_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_ff67df4deb67a69ddb680c797e1\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_574f494375ba65d2c84b6f94bc7\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`content_text\` \`content_text\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`project_id\` \`project_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comment_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comment_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_d6f93329801a93536da4241e386\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_3349532146431047b08bfe61ab6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_18c2493067c11f44efb35ca0e03\``);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`content_text\` \`content_text\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`feed_post_id\` \`feed_post_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`task_id\` \`task_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`due_date\` \`due_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`order_index\` \`order_index\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`closed_at\` \`closed_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department_members\` CHANGE \`position\` \`position\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_members\` CHANGE \`joined_at\` \`joined_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`address\` \`address\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`organization_id\` \`organization_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`uploaded_by\` \`uploaded_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`project_id\` \`project_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar_id\` \`avatar_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_ff67df4deb67a69ddb680c797e1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_574f494375ba65d2c84b6f94bc7\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_d6f93329801a93536da4241e386\` FOREIGN KEY (\`parent_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_3349532146431047b08bfe61ab6\` FOREIGN KEY (\`feed_post_id\`) REFERENCES \`feed_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_18c2493067c11f44efb35ca0e03\` FOREIGN KEY (\`task_id\`) REFERENCES \`tasks\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_78ab9d565fc2593e3b3d1c59dc8\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_44a9b5209cdfd6f72fb09a7c994\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9eecdb5b1ed8c7c2a1b392c28d4\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_5aac2844475acf565d99242b7d1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_71070628c130f2c9cd3cd5f082f\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_700b0b13f494cb37b6ca929e79b\` FOREIGN KEY (\`parent_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`department_members\` ADD CONSTRAINT \`FK_7d7af06fba109a8730e533c3e8d\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`department_members\` ADD CONSTRAINT \`FK_95e0d0606aaac9668e404cff143\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f3a7c9411eaa5f9cbc5363de331\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_385dd167bc3fe894f301c7537bb\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_63c92c51cd7fd95c2d79d709b61\` FOREIGN KEY (\`uploaded_by\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_b3c17c323fdc479a109e517f138\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_c3401836efedec3bec459c8f818\` FOREIGN KEY (\`avatar_id\`) REFERENCES \`files\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_c3401836efedec3bec459c8f818\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_b3c17c323fdc479a109e517f138\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_63c92c51cd7fd95c2d79d709b61\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_385dd167bc3fe894f301c7537bb\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f3a7c9411eaa5f9cbc5363de331\``);
        await queryRunner.query(`ALTER TABLE \`department_members\` DROP FOREIGN KEY \`FK_95e0d0606aaac9668e404cff143\``);
        await queryRunner.query(`ALTER TABLE \`department_members\` DROP FOREIGN KEY \`FK_7d7af06fba109a8730e533c3e8d\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_700b0b13f494cb37b6ca929e79b\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_71070628c130f2c9cd3cd5f082f\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_5aac2844475acf565d99242b7d1\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9eecdb5b1ed8c7c2a1b392c28d4\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_44a9b5209cdfd6f72fb09a7c994\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_78ab9d565fc2593e3b3d1c59dc8\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_18c2493067c11f44efb35ca0e03\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_3349532146431047b08bfe61ab6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_d6f93329801a93536da4241e386\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_574f494375ba65d2c84b6f94bc7\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_ff67df4deb67a69ddb680c797e1\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar_id\` \`avatar_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`project_id\` \`project_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`uploaded_by\` \`uploaded_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`organization_id\` \`organization_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`address\` \`address\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organization_members\` CHANGE \`joined_at\` \`joined_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`department_members\` CHANGE \`position\` \`position\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`closed_at\` \`closed_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`order_index\` \`order_index\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`due_date\` \`due_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`task_id\` \`task_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`feed_post_id\` \`feed_post_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`content_text\` \`content_text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_18c2493067c11f44efb35ca0e03\` FOREIGN KEY (\`task_id\`) REFERENCES \`tasks\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_3349532146431047b08bfe61ab6\` FOREIGN KEY (\`feed_post_id\`) REFERENCES \`feed_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_d6f93329801a93536da4241e386\` FOREIGN KEY (\`parent_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comment_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`project_id\` \`project_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`content_text\` \`content_text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_574f494375ba65d2c84b6f94bc7\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_ff67df4deb67a69ddb680c797e1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_post_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`task_logs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`task_assignees\` CHANGE \`assigned_at\` \`assigned_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`FK_b3c17c323fdc479a109e517f138\` ON \`files\` (\`project_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_63c92c51cd7fd95c2d79d709b61\` ON \`files\` (\`uploaded_by\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_385dd167bc3fe894f301c7537bb\` ON \`files\` (\`organization_id\`)`);
    }

}
