import { MigrationInterface, QueryRunner } from "typeorm";

export class ModuleChatNoti1766636264118 implements MigrationInterface {
    name = 'ModuleChatNoti1766636264118'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_a1a3fcfc03bcc07336f7016933b\``);
        await queryRunner.query(`CREATE TABLE \`chat_room_members\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`role\` enum ('owner', 'admin', 'member') NOT NULL DEFAULT 'member', \`joined_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`last_read_at\` timestamp NULL, \`room_id\` int NOT NULL, \`organization_member_id\` int NULL, \`last_read_message_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_rooms\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`type\` enum ('direct', 'group', 'project') NOT NULL DEFAULT 'direct', \`name\` varchar(255) NULL, \`is_private\` tinyint NOT NULL DEFAULT 0, \`created_by_member_id\` int NULL, \`organization_id\` int NOT NULL, \`project_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_message_attachments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`message_id\` int NOT NULL, \`file_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_message_mentions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`message_id\` int NOT NULL, \`organization_member_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`content_json\` json NOT NULL, \`content_text\` text NULL, \`type\` enum ('text', 'file', 'system', 'reply') NOT NULL DEFAULT 'text', \`is_system\` tinyint NOT NULL DEFAULT 0, \`reply_to_message_id\` int NULL, \`organization_id\` int NOT NULL, \`room_id\` int NOT NULL, \`sender_member_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reactions\` (\`reaction\` enum ('like', 'love', 'care', 'haha', 'wow', 'sad', 'angry') NOT NULL, \`message_id\` int NULL, \`organization_member_id\` int NOT NULL, \`comment_id\` int NULL, \`feed_post_id\` int NULL, PRIMARY KEY (\`reaction\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`type\` enum ('system_announcement', 'system_maintenance', 'system_update', 'system_warning', 'system_error', 'org_invite', 'org_role_changed', 'org_removed', 'project_invite', 'project_role_changed', 'project_updated', 'project_archived', 'task_created', 'task_assigned', 'task_unassigned', 'task_status_changed', 'task_deadline_reminder', 'task_overdue', 'task_commented', 'task_mentioned', 'chat_message', 'chat_mention', 'chat_room_invite', 'user_mentioned', 'profile_updated', 'password_changed') NOT NULL DEFAULT 'system_announcement', \`entity_type\` enum ('organization', 'project', 'task', 'chat_message', 'user', 'system') NOT NULL DEFAULT 'system', \`entity_id\` int NULL, \`level\` enum ('info', 'warning', 'error', 'success') NOT NULL DEFAULT 'info', \`is_read\` tinyint NOT NULL DEFAULT 0, \`read_at\` tinyint NOT NULL DEFAULT 0, \`content\` json NOT NULL, \`organization_id\` int NOT NULL, \`receiver_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`task_assignees\` CHANGE \`assigned_at\` \`assigned_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`task_logs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_post_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_ff67df4deb67a69ddb680c797e1\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_574f494375ba65d2c84b6f94bc7\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`content_text\` \`content_text\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`project_id\` \`project_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comment_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comment_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_d6f93329801a93536da4241e386\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_3349532146431047b08bfe61ab6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_18c2493067c11f44efb35ca0e03\``);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`content_text\` \`content_text\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`feed_post_id\` \`feed_post_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`task_id\` \`task_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_78ab9d565fc2593e3b3d1c59dc8\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`due_date\` \`due_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`order_index\` \`order_index\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`closed_at\` \`closed_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_5aac2844475acf565d99242b7d1\``);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_700b0b13f494cb37b6ca929e79b\``);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department_members\` CHANGE \`position\` \`position\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_members\` CHANGE \`joined_at\` \`joined_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f3a7c9411eaa5f9cbc5363de331\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`address\` \`address\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_385dd167bc3fe894f301c7537bb\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_63c92c51cd7fd95c2d79d709b61\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_b3c17c323fdc479a109e517f138\``);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`organization_id\` \`organization_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`uploaded_by\` \`uploaded_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`project_id\` \`project_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_c3401836efedec3bec459c8f818\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar_id\` \`avatar_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` ADD CONSTRAINT \`FK_58f6a1eac4ffde565c8b078bf4e\` FOREIGN KEY (\`room_id\`) REFERENCES \`chat_rooms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` ADD CONSTRAINT \`FK_199f43df00b1d3e9666a43e8209\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` ADD CONSTRAINT \`FK_2fa8a41905b81ad15086de05dd2\` FOREIGN KEY (\`last_read_message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` ADD CONSTRAINT \`FK_eed7987ca0966c8b0a43cf47d62\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` ADD CONSTRAINT \`FK_2551ba59c9c655ab1350e949361\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` ADD CONSTRAINT \`FK_c5d47b9b7908c0910fd2441905b\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_message_attachments\` ADD CONSTRAINT \`FK_7ba00841386439fa3dd8a77df98\` FOREIGN KEY (\`message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_message_attachments\` ADD CONSTRAINT \`FK_5f84b702a2ea4d90e03fa5cad37\` FOREIGN KEY (\`file_id\`) REFERENCES \`files\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_message_mentions\` ADD CONSTRAINT \`FK_e1050763f9ca02727ec6315ad18\` FOREIGN KEY (\`message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_message_mentions\` ADD CONSTRAINT \`FK_e1d0d1826c07ffd6c67043d8e33\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_686a3bfebb7545534342c5fa272\` FOREIGN KEY (\`reply_to_message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_c223dac1c7d1c04c8954ce669dc\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_7f52e11d11d4e8cc41224352869\` FOREIGN KEY (\`room_id\`) REFERENCES \`chat_rooms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_60700147737bb92ef38180ede3d\` FOREIGN KEY (\`sender_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_2ee227780745018b358237c0ad7\` FOREIGN KEY (\`message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_1ab94f325afcb93bf455e8578fc\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_bbea5deba8e9118ad08429c9104\` FOREIGN KEY (\`comment_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_f0b3228818cdc69fe8f36f7be52\` FOREIGN KEY (\`feed_post_id\`) REFERENCES \`feed_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_ff67df4deb67a69ddb680c797e1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_574f494375ba65d2c84b6f94bc7\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_a1a3fcfc03bcc07336f7016933b\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_d6f93329801a93536da4241e386\` FOREIGN KEY (\`parent_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_3349532146431047b08bfe61ab6\` FOREIGN KEY (\`feed_post_id\`) REFERENCES \`feed_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_18c2493067c11f44efb35ca0e03\` FOREIGN KEY (\`task_id\`) REFERENCES \`tasks\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_78ab9d565fc2593e3b3d1c59dc8\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_5aac2844475acf565d99242b7d1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_700b0b13f494cb37b6ca929e79b\` FOREIGN KEY (\`parent_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_cb7b1fb018b296f2107e998b2ff\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_343c8ee2cd2f4036f2a3423989e\` FOREIGN KEY (\`receiver_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f3a7c9411eaa5f9cbc5363de331\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_385dd167bc3fe894f301c7537bb\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_63c92c51cd7fd95c2d79d709b61\` FOREIGN KEY (\`uploaded_by\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_b3c17c323fdc479a109e517f138\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_c3401836efedec3bec459c8f818\` FOREIGN KEY (\`avatar_id\`) REFERENCES \`files\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_c3401836efedec3bec459c8f818\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_b3c17c323fdc479a109e517f138\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_63c92c51cd7fd95c2d79d709b61\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_385dd167bc3fe894f301c7537bb\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f3a7c9411eaa5f9cbc5363de331\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_343c8ee2cd2f4036f2a3423989e\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_cb7b1fb018b296f2107e998b2ff\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_700b0b13f494cb37b6ca929e79b\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_5aac2844475acf565d99242b7d1\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_78ab9d565fc2593e3b3d1c59dc8\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_18c2493067c11f44efb35ca0e03\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_3349532146431047b08bfe61ab6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_d6f93329801a93536da4241e386\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_a1a3fcfc03bcc07336f7016933b\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_574f494375ba65d2c84b6f94bc7\``);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` DROP FOREIGN KEY \`FK_ff67df4deb67a69ddb680c797e1\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_f0b3228818cdc69fe8f36f7be52\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_bbea5deba8e9118ad08429c9104\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_1ab94f325afcb93bf455e8578fc\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_2ee227780745018b358237c0ad7\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_60700147737bb92ef38180ede3d\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_7f52e11d11d4e8cc41224352869\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_c223dac1c7d1c04c8954ce669dc\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_686a3bfebb7545534342c5fa272\``);
        await queryRunner.query(`ALTER TABLE \`chat_message_mentions\` DROP FOREIGN KEY \`FK_e1d0d1826c07ffd6c67043d8e33\``);
        await queryRunner.query(`ALTER TABLE \`chat_message_mentions\` DROP FOREIGN KEY \`FK_e1050763f9ca02727ec6315ad18\``);
        await queryRunner.query(`ALTER TABLE \`chat_message_attachments\` DROP FOREIGN KEY \`FK_5f84b702a2ea4d90e03fa5cad37\``);
        await queryRunner.query(`ALTER TABLE \`chat_message_attachments\` DROP FOREIGN KEY \`FK_7ba00841386439fa3dd8a77df98\``);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` DROP FOREIGN KEY \`FK_c5d47b9b7908c0910fd2441905b\``);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` DROP FOREIGN KEY \`FK_2551ba59c9c655ab1350e949361\``);
        await queryRunner.query(`ALTER TABLE \`chat_rooms\` DROP FOREIGN KEY \`FK_eed7987ca0966c8b0a43cf47d62\``);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` DROP FOREIGN KEY \`FK_2fa8a41905b81ad15086de05dd2\``);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` DROP FOREIGN KEY \`FK_199f43df00b1d3e9666a43e8209\``);
        await queryRunner.query(`ALTER TABLE \`chat_room_members\` DROP FOREIGN KEY \`FK_58f6a1eac4ffde565c8b078bf4e\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar_id\` \`avatar_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_c3401836efedec3bec459c8f818\` FOREIGN KEY (\`avatar_id\`) REFERENCES \`files\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`project_id\` \`project_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`uploaded_by\` \`uploaded_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`organization_id\` \`organization_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_b3c17c323fdc479a109e517f138\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_63c92c51cd7fd95c2d79d709b61\` FOREIGN KEY (\`uploaded_by\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_385dd167bc3fe894f301c7537bb\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`address\` \`address\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f3a7c9411eaa5f9cbc5363de331\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_members\` CHANGE \`joined_at\` \`joined_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`department_members\` CHANGE \`position\` \`position\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_700b0b13f494cb37b6ca929e79b\` FOREIGN KEY (\`parent_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_5aac2844475acf565d99242b7d1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`closed_at\` \`closed_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`order_index\` \`order_index\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`due_date\` \`due_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_78ab9d565fc2593e3b3d1c59dc8\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`task_id\` \`task_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`feed_post_id\` \`feed_post_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`content_text\` \`content_text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_18c2493067c11f44efb35ca0e03\` FOREIGN KEY (\`task_id\`) REFERENCES \`tasks\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_3349532146431047b08bfe61ab6\` FOREIGN KEY (\`feed_post_id\`) REFERENCES \`feed_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_d6f93329801a93536da4241e386\` FOREIGN KEY (\`parent_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comment_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`project_id\` \`project_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`created_by_member_id\` \`created_by_member_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`content_text\` \`content_text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_574f494375ba65d2c84b6f94bc7\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_posts\` ADD CONSTRAINT \`FK_ff67df4deb67a69ddb680c797e1\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feed_post_attachments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`feed_posts_mentions\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`task_logs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`task_assignees\` CHANGE \`assigned_at\` \`assigned_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`reactions\``);
        await queryRunner.query(`DROP TABLE \`chat_messages\``);
        await queryRunner.query(`DROP TABLE \`chat_message_mentions\``);
        await queryRunner.query(`DROP TABLE \`chat_message_attachments\``);
        await queryRunner.query(`DROP TABLE \`chat_rooms\``);
        await queryRunner.query(`DROP TABLE \`chat_room_members\``);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_a1a3fcfc03bcc07336f7016933b\` FOREIGN KEY (\`created_by_member_id\`) REFERENCES \`organization_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
